# File: azure-pipelines.yml

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo "ubuntu-latest"

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: echo "macOS-latest"

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo "windows-latest"