name: CI

on: [push]

jobs:
  validate:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [macos-latest,windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Init & Update Submodules
        run: git submodule update --init --recursive --remote

      - name: Install Pre-Requisites macOS
        if: startsWith(runner.os, 'macOS')
        run: |
          brew install --cask multipass
          brew install coreutils
          brew install bats
          alias readlink=greadlink

      - name: Install Pre-Requisites Linux
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo add-apt-repository ppa:duggan/bats
          sudo apt-get update
          sudo apt-get install bats
          sudo snap install multipass --classic
          sudo snap install docker

      - name: Install Pre-Requisites Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          iwr -useb get.scoop.sh | iex
          echo "::add-path::C:\Users\runneradmin\scoop\shims"
          npm install -g bats
          scoop install git
          scoop install docker
          scoop install docker-compose

      ## Not the ci/check_bats.bash do not send the failures to the GitHub Actions
      - name: Test
        shell: bash
        run: |
          ci/check_bats.bash unit
          ci/check_bats.bash integration

      ### @TODO: Test suite for  Docker yet to be ported for Mac & Windows
      ### Its due to the Limitation of GitHub Default Runners
      ### Mac: https://github.community/t5/GitHub-Actions/Why-is-Docker-not-installed-on-macOS/m-p/39364
      ### Windows : https://github.community/t5/GitHub-Actions/How-to-use-Linux-Docker-container-on-Windows-VM/m-p/38535
      ### Paid Self Hosted Runner is Required - so the Technical Debit is Parked

      - name: Docker Integration Test (Linux)
        if: startsWith(runner.os, 'Linux')
        run: |
          ci/check_bats.bash host_precondition
          ci/check_bats.bash host_docker_precondition
          ci/check_bats.bash docker

      - name: Docker Integration Test (Windows)
        if: startsWith(runner.os, 'Windows')
        shell: bash
        run: |
          ci/check_bats.bash host_docker_precondition
